# black list wip branches, however if pull requests are created for one then
# travis should build it
branches:
  except:
    - /^(wip|WIP)(-|_).*$/
notifications:
  irc:
    channels:
      - "irc.freenode.org#ccdevs"
    on_success: change
    on_failure: always
  email:
    recipients:
      - stephen.bannasch@gmail.com
      - sfentress@concord.org
      - rpk@pobox.com
      - janikpiotrek@gmail.com
      - scytacki@concord.org
    on_success: change
    on_failure: always
language: ruby
rvm:
  - "2.0.0"
before_install: sudo apt-get install libicu-dev
bundler_args: --without development
before_script:
  - travis_retry npm install
  - make prepare-submodules
script: "time make public"
