---
# environment can be 'development' or 'production'
:environment: development
# :lab_root_url:
#   :production: //lab-framework.concord.org/lab
#   :staging:    //lab-framework.staging.concord.org/lab
#   :dev:        //lab-framework.dev.concord.org/lab
#   :local:      //localhost:9191/lab
:jsconfig:
  # This can be set optionally set to true to disable links to DataGames and Java models.
  # Used only by application.js (SITE_CONFIG).
  :static: false
  # Used both by application.js (SITE_CONFIG) and to set Lab.config.dataGamesProxyPrefix.
  :dataGamesProxyPrefix: ""
:google_analytics:
  :account_id:
# password and alias for Java siging certificate.
:java:
  :password: abc123
  :alias: lab-sample-keystore
  :keystore_path: config/lab-sample-keystore.jks
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.concord.org
    :branch: production
  - :name: lab-staging
    :url: lab-staging.concord.org
    :branch: staging
  - :name: lab-dev
    :url: lab.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev/
  - :name: lab2-dev
    :url: lab2.dev.concord.org
    :branch: inquiry-space
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev2/
  - :name: lab3-dev
    :url: lab3.dev.concord.org
    :branch: master
    :dataGamesProxyPrefix: DataGames/Games/concord/lab.dev3/
  :group_name: lab.dev
  :zone_domain: concord.org.
  :zone_records_name: dev.concord.org
  :pem:
    :name: lab-dev
    :path: ~/.ec2
