---
# environment can be 'development' or 'production'
:environment: development
# use the lab_root_url to override the default lab urls used in
# the embeddable-*.html files, e.g.:
# :lab_root_url:
#   :production:  //lab-framework-s3.concord.org/version/<ver>/lab
#   :staging:     //lab-framework-s3.concord.org/version/<ver>/lab
#   :development: //lab-framework-s3.concord.org/branch/<branch>/lab
#   :default:     //lab-framework-s3.concord.org/branch/<branch>/lab
#   :local:       //localhost:9191/lab
:jsconfig:
  # Used both by application.js (SITE_CONFIG) and to set Lab.config.dataGamesProxyPrefix.
  :dataGamesProxyPrefix: ""
:google_analytics:
  :account_id:
# deploy configuration for working with Amazon Web Services
:deploy:
  :targets:
  - :name: lab
    :url: lab.concord.org
    :branch: master
  - :name: lab-staging
    :url: lab-staging.concord.org
    :branch: master
  - :name: lab-dev
    :url: lab.dev.concord.org
    :branch: master
  - :name: lab2-dev
    :url: lab2.dev.concord.org
    :branch: inquiry-space
  - :name: lab3-dev
    :url: lab3.dev.concord.org
    :branch: master
  :group_name: lab.dev
  :zone_domain: concord.org.
  :zone_records_name: dev.concord.org
  :pem:
    :name: lab-dev
    :path: ~/.ec2
