s3_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret: <%= ENV['S3_SECRET_KEY'] %>
s3_bucket: interactives-s3.concord.org
s3_endpoint: us-east-1
gzip: true

<% if ENV['TRAVIS_BRANCH'] == 'master' %>
# In this case we are going to deploy this branch to the top level of the domain
# and version/<SITE_VERSION>, so we need to ignore the old versions and branch folders.
ignore_on_server: ^(version/(?!<%= Regexp.escape(ENV['SITE_VERSION']) %>/)|branch/)
<% else %>
# In this case we are going to deploy this code to a subfolder of the branch folder.
# So ignore everything except this folder.
ignore_on_server: ^(?!<%= Regexp.escape(ENV['DEPLOY_DIR']) %>/)
<% end %>
max_age:
  "version/**/*": 300 # 5 minutes in seconds
  "branch/**/*": 300  # 5 minutes in seconds
# currently the production files at the root are not set with a max_age this is the
# same as what is done currently.
