---
# environment can be 'development' or 'production'.
:environment: production
# use the lab_root_url to override the default lab urls used in
# the embeddable-*.html files, e.g.:
# :lab_root_url:
#   :production:  //lab-framework-s3.concord.org/version/<ver>/lab
#   :staging:     //lab-framework-s3.concord.org/version/<ver>/lab
#   :development: //lab-framework-s3.concord.org/branch/<branch>/lab
#   :default:     //lab-framework-s3.concord.org/branch/<branch>/lab
#   :local:       //localhost:9191/lab
:lab_root_url:
  :default: //lab-framework.concord.org/version/1.0.1-pre.2/lab